### ISSUE TITLE
blacklist job

### ISSUE THREAD

**Issue by kFxDaKing** [P4NDAzzGaming/esx_speedcamera#3]
Is there any way to blacklist jobs? police, ambulance, fbi etc, cause it doesnt works for car names.

**Comment by i-kulgu** [comment]
You can put this from line 22:

```
RegisterNetEvent('esx:setJob')
AddEventHandler('esx:setJob', function(job)
	ESX.PlayerData.job = job
end)
```

Then remove the if rules from 119 - 127 where the cars are blacklisted and put this instead:

`if ESX.PlayerData.job ~= nil and ESX.PlayerData.job.name == 'police' then`

Not tested it but this should work.
